import Vue from 'vue'
export default {
  namespaced:true,
  state: {
	  shelf:[
		  {name:'',id:''}
	  ],
	  sort:[
		  {'name':'综合',id:0},
		  {'name':'销量',id:1},
		  {'name':'人气',id:2},
		  {'name':'价格',id:3}
	  ],
	  product:[
		  {
			  follow:false,
			  img:'https://nuskindevelop.oss-cn-shenzhen.aliyuncs.com/phone/NF80clypcwPftxY6LKp6TH0phSx3wy.jpg',
			  band:'王牌ageLOC',
			  name:'商品标题',
			  taxes:'100',
			  price:'100',
			  pId:'1'
		  },
		  {
		  			  follow:false,
		  			  img:'https://nuskindevelop.oss-cn-shenzhen.aliyuncs.com/phone/NF80clypcwPftxY6LKp6TH0phSx3wy.jpg',
		  			  band:'王牌ageLOC',
		  			  name:'商品标题',
		  			  taxes:'100',
		  			  price:'100',
		  			  pId:'1'
		  },
		  {
		  			  follow:false,
		  			  img:'https://nuskindevelop.oss-cn-shenzhen.aliyuncs.com/phone/NF80clypcwPftxY6LKp6TH0phSx3wy.jpg',
		  			  band:'王牌ageLOC',
		  			  name:'商品标题',
		  			  taxes:'100',
		  			  price:'100',
		  			  pId:'2'
		  },
		  {
		  			  follow:false,
		  			  img:'https://nuskindevelop.oss-cn-shenzhen.aliyuncs.com/phone/NF80clypcwPftxY6LKp6TH0phSx3wy.jpg',
		  			  band:'王牌ageLOC',
		  			  name:'商品标题',
		  			  taxes:'100',
		  			  price:'100',
		  			  pId:'3'
		  },
		  {
		  			  follow:false,
		  			  img:'https://nuskindevelop.oss-cn-shenzhen.aliyuncs.com/phone/NF80clypcwPftxY6LKp6TH0phSx3wy.jpg',
		  			  band:'王牌ageLOC',
		  			  name:'商品标题',
		  			  taxes:'100',
		  			  price:'100',
		  			  pId:'4'
		  },
		  {
		  			  follow:false,
		  			  img:'https://nuskindevelop.oss-cn-shenzhen.aliyuncs.com/phone/NF80clypcwPftxY6LKp6TH0phSx3wy.jpg',
		  			  band:'王牌ageLOC',
		  			  name:'商品标题',
		  			  taxes:'100',
		  			  price:'100',
		  			  pId:'5'
		  }
	  ]
  },
  mutations: {
	  clear(state, data){
		  Vue.set(state,'shelf',[])
		  Vue.set(state,'sort',[])
		  Vue.set(state,'product',[])
	  }
  },
  actions:{
	  clear(context,data){
		  context.commit("clear");
	  },
	  initReady(context,data){
		  context.commit("initReady");
	  }
  }
 }